### ISSUE TITLE
Custom Plugins

### ISSUE THREAD

**Issue by auguwu** [PassTheWessel/kirbe#1]
Add custom plugins like Express has.

i.e: `kirbe-owo`

```js
kirbe.useMiddleware(new KirbeOwO());
```

similar to expressjs

**Comment by PassTheWessel** [comment]
I will try my best to add this as soon as i can, thanks for your request!

**Comment by PassTheWessel** [comment]
I've tried my best to add this to kirbe, feel free to ask me if you find any problems with middleware :octocat:
